// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SaldoBancarioAPI.Data;

namespace SaldoBancarioAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("SaldoBancarioAPI.Model.Importacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataImportacao");

                    b.Property<string>("NomeArquivo");

                    b.HasKey("Id");

                    b.ToTable("Importacoes");
                });

            modelBuilder.Entity("SaldoBancarioAPI.Model.Moeda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Compra");

                    b.Property<DateTime>("DataCotacao");

                    b.Property<string>("Nome");

                    b.Property<decimal>("Variacao");

                    b.Property<decimal>("Venda");

                    b.HasKey("Id");

                    b.ToTable("Moedas");
                });

            modelBuilder.Entity("SaldoBancarioAPI.Model.Movimentacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataMovimento");

                    b.Property<string>("Descricao");

                    b.Property<Guid?>("ImportacaoId");

                    b.Property<decimal>("SaldoAtual");

                    b.Property<decimal>("Valor");

                    b.HasKey("Id");

                    b.HasIndex("ImportacaoId");

                    b.ToTable("Movimentacoes");
                });

            modelBuilder.Entity("SaldoBancarioAPI.Model.Movimentacao", b =>
                {
                    b.HasOne("SaldoBancarioAPI.Model.Importacao", "Importacao")
                        .WithMany("Movimentacoes")
                        .HasForeignKey("ImportacaoId");
                });
#pragma warning restore 612, 618
        }
    }
}
